from enum import Enum


class TicketHistoryAction(str, Enum):
    CREATED = "CREATED"
    TITLE_CHANGED = "TITLE_CHANGED"
    DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED"
    CATEGORY_CHANGED = "CATEGORY_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    DUE_DATE_CHANGED = "DUE_DATE_CHANGED"
    ASSIGNED = "ASSIGNED"
    ASSIGNEE_CHANGED = "ASSIGNEE_CHANGED"
    ASSIGNEE_REMOVED = "ASSIGNEE_REMOVED"
    STATUS_CHANGED = "STATUS_CHANGED"
    COMPLETED = "COMPLETED"
    REOPENED = "REOPENED"
    CANCELLED = "CANCELLED"
